services:
  mikochi:
    image: zer0tonin/mikochi:latest-armv7
    user: "1000:1000"
    ports:
      - 8082:8080
    volumes:
      - /shared/mikochi:/data
    environment:
      USERNAME: test
      PASSWORD: ${PASSWORD}
    restart: unless-stopped
    logging:
      driver: local
