version: '3'
services:
  mikochi:
    image: zer0tonin/mikochi:latest-armv7
    volumes:
      - /shared/mikochi:/data
    ports:
      - 8082:8080
    environment:
      USERNAME: test
      PASSWORD: ${PASSWORD}
    restart: always
