services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    user: "1000:1000"
    ports:
      - 8083:3001
    environment: [ ]
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: local
