services:
  stash:
    image: stashapp/stash:latest
    user: "1000:1000"
    ports:
      - 8084:9999
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/root/.stash
      # Data directory
      - /shared/Videos/favorite:/data
      - ./metadata:/metadata
      - ./cache:/cache
      - ./blobs:/blobs
      - ./generated:/generated
    restart: unless-stopped
    logging:
      driver: local
